apiVersion: skaffold/v2beta19
kind: Config
build:
  artifacts:
  - image: registry.ks.io/amorgant/server-debug
    docker:
      dockerfile: docker/debug/Dockerfile
    context: .
    sync: 
      auto: true 
  local:
    push: true
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yml
